### PR TITLE
Lock is now able to receive commands. Light is turned on or off indic…

### PR DESCRIPTION
**Pull request by LarsHoldijk**
…ating the door being locked or unlocked.

### CODE REVIEW

**Review by suzannemaquelin — CHANGES_REQUESTED** [review]
Can the name of the file loop.ino be changed? It is not very descriptive

**Comment by markhelmus** [comment]
The code looks good, but shouldn't this branch be merged into the development branch instead of the master branch?

**Review by Feikoritsema — APPROVED** [review]
It all looks fine to me, only one small comment, after declaring a function you sometimes add a space before the { and sometimes not. Not a problem, but consistency is always good.

**Review by markhelmus — APPROVED** [review]
Changed branch, code still looks good.

**Review by suzannemaquelin — APPROVED** [review]

**Pull request merged**
